trigger:
  paths:
    exclude:
      - 'WebApi'
      - 'Angular'

pool:
  vmImage: ubuntu-latest

steps:

- task: CmdLine@2
  inputs:
    script: |
      echo  '$(System.DefaultWorkingDirectory)'
      echo  '$(Agent.BuildDirectory)'
      ls